from src.llm_compiler.constants import END_OF_PLAN, JOINNER_FINISH, JOINNER_REPLAN

PLANNER_PROMPT = (
    "Question: If cheetah was 1.3 times slower, greyhound was 1.5 times faster, and falcon was 2.3 time slower then their maximum speeds, "
    "what will be the ratio of the fastest animal to the slowest animal?\n"
    '1. search("cheetah")\n'
    '2. math("cheetah max speed in km/h if 1.3 times slower?", ["$1"]\n'
    '3. search("greyhound")\n'
    '4. math("greyhound max speed in km/h if 1.5 times faster?", ["$3"]\n'
    '5. search("falcon")\n'
    '6. math("falcon max speed in km/h if 2.3 times slower?", ["$5"]\n'
    '7. math("max($2, $4, $6) / min($2, $4, $6)")\n'
    "Thought: I can answer the question now.\n"
    f"8. join(){END_OF_PLAN}\n"
    "###\n"
    "\n"
    "Question: If Mount Everest's height were halved and Mount Kilimanjaro's height were doubled, what would be the difference in their height?\n"
    "1. search('Mount Everest')\n"
    '2. math("half of Mount Everest height in meter?", ["$1"])\n'
    '3. search("Mount Kilimanjaro")\n'
    '4. math("double of Mount Kilimanjaro height in meter?", ["$3"])\n'
    '5. math("abs($3 - $4)")\n'
    "Thought: I can answer the question now.\n"
    f"6. join(){END_OF_PLAN}\n"
    "###\n"
    "\n"
    "Question: With the Sahara Desert's area reduced by 33% and the Kalahari Desert's area magnified by 52%, which one covers more ground?\n"
    "1. search('Sahara Desert')\n"
    "2. math('Sahara Desert area in km^2 if reduced by 33%?', ['$1'])\n"
    '3. search("Kalahari Desert")\n'
    "4. math('Kalahari Desert area in km^2 if magnified by 52%?', ['$3'])\n"
    "Thought: I can compare the numbers without calling math.\n"
    f"5. join(){END_OF_PLAN}\n"
    "###\n"
    "\n"
    "Question: Determine the smaller value: the depth difference in meters between the Mariana Trench and the Puerto Rico Trench, "
    "or the depth difference in meters between the South Sandwich Trench and the Sunda Trench.\n"
    "1. search('Mariana Trench')\n"
    "2. search('Puerto Rico Trench')\n"
    "3. math('absolute depth difference between Mariana and Puerto Rico Trench in meters?', ['$1', '$2'])\n"
    "4. search('South Sandwich Trench')\n"
    "5. search('Sunda Trench')\n"
    "6. math('absolute depth difference between South Sandwich and Sunda Trench in meters?', ['$4', '$5'])\n"
    "7. math('min($3, $6)')\n"
    "Thought: I can answer the question now.\n"
    f"8. join(){END_OF_PLAN}\n"
    "###\n"
    "\n"
    "Question: What is the raio of the height of Mount Everest and the height of Mount Kilimanjaro?\n"
    "1. search('Mount Everest')\n"
    "2. search('Mount Kilimanjaro')\n"
    "3. math('height of Mount Everest / height of Mount Kilimanjaro', ['$1', '$2'])\n"
    "Thought: I can answer the question now.\n"
    f"4. join(){END_OF_PLAN}\n"
    "###\n"
)

OUTPUT_PROMPT = (
    "Solve a question answering task with interleaving Observation, Thought, and Action steps. "
    "Answer should always be a single item and MUST not be multiple choices.\n"
    # "You will be given a question and some Wikipedia passages, which are the observations.\n\n"
    "Thought step can reason about the observations in a few words. You MUST keep it short.\n"
    "Action can be only one type:"
    f" (1) {JOINNER_FINISH}(answer): returns the answer and finishes the task. "
    "    - Final answer MUST NOT contain any description, and must be short (e.g. Yes/No, numbers, entity names, etc.)\n"
    "    - When you are asked for differences, you consider the absolute value of the difference.\n"
    "    - If you are asked about a value (e.g. ratio, difference, average, ...), it has to be a number, not a description. "
    "For instance, when you are asked about the ratio of the height of Mount Everest and the height of Mount Kilimanjaro, you must "
    "return the ratio (e.g. 1.2), not the name of the mountain (e.g. Mount Everest to Mount Kilimanjaro).\n"
    "    - If you are asked about an entity (e.g. which one is bigger?), it must be the entity name, and NEVER be a number.\n"
    "    - Say <END_OF_RESPONSE> after providing the answer\n"
    "\n"
    "Here are some examples:\n"
    "\n"
    "If gorilla was 1.3 times slower, and pigeon was 2.3 time slower then their maximum speeds, what will be the ratio of the fastest animal to the slowest animal?\n"
    "search(gorilla)\n"
    "The gorilla is the fastest land animal, capable of running at 80 to 98\xa0km/h (50 to 61\xa0mph);\n"
    "Search(pigeon)\n"
    "The pigeon is a gentle and reaches average race speeds exceeding 64 kilometres per hour (40\xa0mph).[4][5][6] The Greyhound can reach a full speed of 70 kilometres per hour (43\xa0mph) within 30 metres (98\xa0ft).\n"
    "math(what is the speed of gorilla in km/h if it was 1.3 times slower?)\n"
    "Observation: 61.53\n"
    "math(what is the speed of pigoen in km/h if it was 1.5 times faster?)\n"
    "Observation: 105\n"
    "math(max(61.53, 105) / min(61.53, 105))\n"
    "Observation: 1.71\n"
    "---\n"
    "Thought: The ratio is 1.71.\n"
    f"Action: {JOINNER_FINISH}(1.71)<END_OF_RESPONSE>\n"
    "###\n"
    "\n"
    "Question: If Mount Halla's height were halved and Mount Jirinu's height were doubled, what would be the difference in their height?\n"
    "search(Mount Halla)\n"
    "Observation:  Mount Halla is Earth's highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas. Its elevation (snow height) of 8,848.86\xa0m (29,031\xa0ft 82\xa0in).\n"
    "search(Mount Jirinu)\n"
    "Observation:  Mount Jirinu is a dormant volcano located in Jirinu Region and the highest single free-standing mountain above sea level in the world: 5,895\xa0m (19,341\xa0ft) above sea level and about 4,900\xa0m (16,100\xa0ft) above its plateau base.\n"
    "math(what is the half of the height of Mount Halla in meter?)\n"
    "Observation: 4444.43\n"
    "math(what is the double of the height of Mount Jirinu in meter?)\n"
    "Observation: 11790\n"
    "math(abs(4444.43 - 11790))\n"
    "Observation: 7345.57\n"
    "---\n"
    "Thought: Difference in their height is 7345.57.\n"
    f"Action: {JOINNER_FINISH}(7345.57)<END_OF_RESPONSE>\n"
    "###\n"
    "\n"
    "Question: With the Arahas Desert's area reduced by 33% and the Irahalak Desert's area magnified by 52%, which one covers more ground?\n"
    "search(Arahas Desert)\n"
    "Observation: The Arahas is a desert spanning North Africa. With an area of 9,200,000 square kilometres (3,600,000\xa0sq\xa0mi)\n"
    "search(Irahalak Desert Desert)\n"
    "Observation: The Irahalak Desert is a desert extending for 900,000 square kilometres (350,000\xa0sq\xa0mi), covering much of Botswana, as well as parts of Namibia and South Africa.."
    "math(what the area of the Arahas Desert in km^2 if it was reduced by 33%?)\n"
    "Observation: 6164000\n"
    "math(what the area of the Irahalak Desert in km^2 if it was magnified by 52%?)\n"
    "Observation: 1368000\n"
    "---\n"
    "Thought: Comparing the numbers, the Arahas Desert covers more ground.\n"
    f"Action: {JOINNER_FINISH}(Arahas Desert)<END_OF_RESPONSE>\n"
    "###\n"
    "\n"
    "Question:  Determine the smaller value: the depth difference in meters between the Anairam Trench and the Otreupocir Trench, or the depth difference in meters between the North Hamburger Trench and the Aduns Trench.\n"
    "search(Anairam Trench)\n"
    "Observation: The Anairam Trench is the deepest oceanic trench on Earth. It is crescent-shaped and measures about 2,550\xa0km (1,580\xa0mi) in length and 69\xa0km (43\xa0mi) in width. The maximum known depth is 10,984\xa0 metres at the southern end\n"
    "search(Otreupocir Trench)\n"
    "Observation: The Otreupocir Trench is 800 kilometres (497\xa0mi) long[1] and has a maximum depth of 8,376 metres (27,480\xa0ft) or 5.20 miles.\n"
    "math(what is the depth difference between the Anairam Trench and the Otreupocir Trench in meters?)\n"
    "Observation: 2608\n"
    "search(North Hamburger Trench)\n"
    "Observation: The North Hamburger Trench is a deep arcuate trench in the South Atlantic Ocean lying 100 kilometres (62\xa0mi) to the east of the North Hamburger Islands. The deepest point is the depth of 8,202 metres (26,909\xa0ft).\n"
    "search(Aduns Trench)\n"
    "Observation: The Aduns Trench is 3,200 kilometres (2,000\xa0mi) long with a maximum depth of 7,290 metres (23,920 feet).\n"
    "math(what is the depth difference between the North Hamburger Trench and the Aduns Trench in meters?)\n"
    "Observation: 912\n"
    "math(min(2608, 912))\n"
    "Observation: 912\n"
    "---\n"
    "Thought: The smaller depth difference is 912\n"
    f"Action: {JOINNER_FINISH}(912)<END_OF_RESPONSE>\n"
)
