from src.llm_compiler.constants import END_OF_PLAN, JOINNER_FINISH

PLANNER_PROMPT = (
    # "Question: Find a movie similar to Interstellar, 2001: A Space Odyssey, The Martian, Star Wars Episode IV - A New Hope\n"
    # "Options:\n"
    # "Saving Private Ryan\n"
    # "Ender's Game\n"
    # "Avatar\n"
    # "Titanic\n"
    # '1. search("Interstellar")\n'
    # '2. search("2001: A Space Odyssey")\n'
    # '3. search("The Martian")\n'
    # '4. search("Star Wars Episode IV - A New Hope")\n'
    # '5. search("Saving Private Ryan")\n'
    # """6. search("Ender's Game")\n"""
    # '7. search("Avatar")\n'
    # '8. search("Titanic")\n'
    # "Thought: I can answer the question now.\n"
    # f"9. join(){END_OF_PLAN}\n"
    # "###\n"
    # "\n"
    "Question: Find a movie similar to Mission Impossible, The Silence of the Lambs, American Beauty, Star Wars Episode IV - A New Hope\n"
    "Options:\n"
    "Austin Powers International Man of Mystery\n"
    "Alesha Popvich and Tugarin the Dragon\n"
    "In Cold Blood\n"
    "Rosetta\n"
    '1. search("Mission Impossible")\n'
    '2. search("The Silence of the Lambs")\n'
    '3. search("American Beauty")\n'
    '4. search("Star Wars Episode IV - A New Hope")\n'
    "5. search(Austin Powers International Man of Mystery)\n"
    "6. search(Alesha Popvich and Tugarin the Dragon)\n"
    "7. search(In Cold Blood)\n"
    "8. search(Rosetta)\n"
    "Thought: I can answer the question now.\n"
    f"9. join(){END_OF_PLAN}\n"
)

OUTPUT_PROMPT = (
    "Solve a question answering task with interleaving Observation, Thought, and Action steps. "
    "Answer should always be a single item and MUST not be multiple choices.\n"
    "You will be given a question and some Wikipedia passages, which are the observations.\n\n"
    "Thought step can reason about the observations in 1-2 sentences, and Action can be only one type:\n"
    f" (1) {JOINNER_FINISH}(answer): returns the answer and finishes the task. "
    "Answer should be short and a single item and MUST not be multiple choices.\n"
    "\nGuidelines:\n"
    f"  - You MUST always output with {JOINNER_FINISH}(answer) even if you are not sure about the answer.\n"
    "   - You MUST Find all movies to make the most informed decision.\n"
    "   - The Observation for some movies may not be available or not relevant to movie information. "
    "If this happens, just ignore it and rely on your own knowledge on that movie.\n"
    "   - When making the final answer, you MUST use both your own knowledge and the information you found. "
    "Information is only there to help you make a better and informed decision.\n"
    "   - You must say <END_OF_RESPONSE> at the end of your response.\n"
    "\n"
    "Here are some examples: \n"
    "\n"
    "Question: Find a movie similar to Interstellar, 2001: A Space Odyssey, The Martian, Star Wars Episode IV - A New Hope\n"
    "Options:\n"
    "Saving Private Ryan\n"
    "Ender's Game\n"
    "Avatar\n"
    "Titanic\n"
    "\n"
    "search(Interstellar)\n"
    "Observation: Interstellar is a 2014 epic science fiction. Set in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.\n"
    "\n"
    "search(2001: A Space Odyssey)\n"
    "Observation: 2001: A Space Odyssey is a 1968 epic science fiction film produced and directed by Stanley Kubrick.\n"
    "\n"
    "search(The Martian)\n"
    "Observation: The Martian is a 2015 science fiction film directed by Ridley Scott and starring Matt Damon. he film depicts an astronaut's lone struggle to survive on Mars after being left behind and the efforts of NASA to rescue him and bring him home to Earth."
    "\n"
    "search(Star Wars Episode IV - A New Hope)\n"
    'Observation: Star Wars is a 1977 American epic space opera film. Set "a long time ago" in a fictional universe where the galaxy is ruled by the tyrannical Galactic Empire, the story focuses on a group of freedom fighters known as the Rebel Alliance, who aim to destroy the Empire\'s newest weapon, the Death Star.\n'
    "\n"
    "search(Saving Private Ryan)\n"
    "Observation: Saving Private Ryan is a 1998 American epic war film. Set in 1944 in France during World War II, it follows a group of soldiers, led by Captain John Miller (Tom Hanks), on their mission to locate Private James Francis Ryan and bring him home safely after his three brothers are killed in action.\n"
    "\n"
    "search(Ender's Game)\n"
    "Observation: Ender's Game is a 1985 military science fiction novel by American author Orson Scott Card. Set at an unspecified date in Earth's future, the novel presents an imperiled humankind after two conflicts with an insectoid alien species they dub \"the buggers\".\n"
    "\n"
    "search(Avatar)\n"
    "Observation: Avatar is a 2009 epic science fiction film. It is the first installment in the Avatar film series. It is set in the mid-22nd century, when humans are colonizing Pandora, a lush habitable moon of a gas giant in the Alpha Centauri star system, in order to mine the valuable mineral unobtanium.\n"
    "\n"
    "search(Titanic)\n"
    "Observation: Titanic is a 1997 American disaster film. Kate Winslet and Leonardo DiCaprio star as members of different social classes who fall in love during the ship's maiden voyage.\n"
    "Thought: Based on my own knowledge and the provided observations, Ender's Game is the most similar.\n"
    f"Action: {JOINNER_FINISH}(Ender's Game)\n"
    "<END_OF_RESPONSE>\n"
    "\n"
    "\n"
    "Question: Find a movie similar to Mission Impossible, The Silence of the Lambs, American Beauty, Star Wars Episode IV - A New Hope\n"
    "Options:\n"
    "Austin Powers International Man of Mystery\n"
    "Alesha Popvich and Tugarin the Dragon\n"
    "In Cold Blood\n"
    "Rosetta\n"
    "\n"
    "search(Mission Impossible)\n"
    "Observation: Mission: Impossible is an American multimedia franchise based on a fictional secret espionage agency known as the Impossible Missions Force (IMF).\n"
    "\n"
    "search(The Silence of the Lambs)\n"
    "Observation: Could not find [The Silence of the Lambs]'\n"
    "\n"
    "search(American Beauty)\n"
    "Observation: Could not find [American Beauty].\n"
    "\n"
    "search(Star Wars Episode IV - A New Hope)\n"
    'Observation: Star Wars is a 1977 American epic space opera film written and directed by George Lucas. Set "a long time ago" in a fictional universe where the galaxy is ruled by the tyrannical Galactic Empire, the story focuses on a group of freedom fighters known as the Rebel Alliance.\n'
    "\n"
    "search(Austin Powers International Man of Mystery)\n"
    "Observation: Austin Powers: International Man of Mystery is a 1997 American spy comedy film. It is the first installment in the Austin Powers series.\n"
    "\n"
    "search(Alesha Popvich and Tugarin the Dragon)\n"
    "Observation: Could not find Alesha Popovich and Tugarin the Dragon.\n"
    "\n"
    "search(In Cold Blood)\n"
    "Observation: In Cold Blood is a non-fiction novel. It details the 1959 murders of four members of the Clutter family in the small farming community of Holcomb, Kansas.. Capote learned of the quadruple murder before the killers were captured, and he traveled to Kansas to write about the crime.\n"
    "\n"
    "search(Rosetta)\n"
    "Observation: Rosetta s a port city of the Nile Delta, 65 km (40 mi) east of Alexandria, in Egypt's Beheira governorate.\n"
    "Thought: Based on my own knowledge and the provided observations, Austin Powers International Man of Mystery is most similar\n"
    f"Action: {JOINNER_FINISH}(Austin Powers International Man of Mystery)\n"
    "<END_OF_RESPONSE>\n"
    "\n"
    "\n"
)
